version: '3.8'

networks:
  cspmexa_net:
    driver: bridge

volumes:
  postgres_auth_data:
  # Para desenvolvimento, podemos persistir node_modules do frontend se não quisermos reconstruir
  # frontend_node_modules:

services:
  # --- Banco de Dados ---
  postgres_auth_db:
    image: postgres:13-alpine
    container_name: cspmexa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-cspmexa_user}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-changeme}
      POSTGRES_DB: ${AUTH_DB_NAME:-cspmexa_db}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_EXPOSED_PORT:-5433}:5432"
    networks:
      - cspmexa_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-cspmexa_user} -d $${POSTGRES_DB:-cspmexa_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Serviços de Backend ---
  auth_service:
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: cspmexa-auth-service
    restart: unless-stopped
    command: python /app/app/main.py # main.py lida com reload via DEBUG_MODE
    environment:
      - DATABASE_URL=postgresql://${AUTH_DB_USER:-cspmexa_user}:${AUTH_DB_PASSWORD:-changeme}@postgres_auth_db:5432/${AUTH_DB_NAME:-cspmexa_db}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?err_jwt_secret_missing}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:?err_google_client_id_missing}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:?err_google_client_secret_missing}
      - GOOGLE_REDIRECT_URI=http://localhost:${API_GATEWAY_PORT:-8050}/api/v1/auth/google/callback
      - FRONTEND_URL_AUTH_CALLBACK=http://localhost:${FRONTEND_PORT:-3000}/auth/callback
      - TOTP_ISSUER_NAME=${TOTP_ISSUER_NAME:-CSPMEXA}
      - DEBUG_MODE=${DEBUG_MODE:-false} # Para hot-reloading
    volumes:
      - ./backend/auth_service:/app # Monta o código para hot-reloading
    ports:
      - "${AUTH_SERVICE_PORT:-8000}:8000"
    networks:
      - cspmexa_net
    depends_on:
      postgres_auth_db:
        condition: service_healthy

  collector_service:
    build:
      context: ./backend/collector_service
      dockerfile: Dockerfile
    container_name: cspmexa-collector-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      - AWS_REGION_NAME=${AWS_REGION_NAME:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-credentials.json
      - GOOGLE_SERVICE_ACCOUNT_KEY_PATH=/app/secrets/gws-sa-key.json
      - GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL=${GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL}
      - GOOGLE_WORKSPACE_CUSTOMER_ID=${GOOGLE_WORKSPACE_CUSTOMER_ID:-my_customer}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - HUAWEICLOUD_SDK_AK=${HUAWEICLOUD_SDK_AK}
      - HUAWEICLOUD_SDK_SK=${HUAWEICLOUD_SDK_SK}
      - HUAWEICLOUD_SDK_PROJECT_ID=${HUAWEICLOUD_SDK_PROJECT_ID}
      - HUAWEICLOUD_SDK_DOMAIN_ID=${HUAWEICLOUD_SDK_DOMAIN_ID}
      # Microsoft 365
      - M365_CLIENT_ID=${M365_CLIENT_ID}
      - M365_CLIENT_SECRET=${M365_CLIENT_SECRET}
      - M365_TENANT_ID=${M365_TENANT_ID}
      - M365_HTTP_CLIENT_TIMEOUT=${M365_HTTP_CLIENT_TIMEOUT:-30}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    volumes:
      - ./backend/collector_service:/app
      # Montar arquivos de credenciais do host para o container.
      # O usuário deve criar uma pasta 'secrets' na raiz e colocar os arquivos lá,
      # ou ajustar os caminhos abaixo e no .env raiz.
      - ${GCP_CREDENTIALS_PATH_HOST:-./secrets/gcp-credentials.json}:/app/secrets/gcp-credentials.json:ro
      - ${GWS_SA_KEY_PATH_HOST:-./secrets/gws-sa-key.json}:/app/secrets/gws-sa-key.json:ro
      # Para credenciais AWS, pode-se montar ~/.aws ou usar variáveis de ambiente.
      # - ~/.aws:/root/.aws:ro
    ports:
      - "${COLLECTOR_SERVICE_PORT:-8001}:8001"
    networks:
      - cspmexa_net

  policy_engine_service:
    build:
      context: ./backend/policy_engine_service
      dockerfile: Dockerfile
    container_name: cspmexa-policy-engine-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      # Aponta para o mesmo DB do auth_service para alertas (ALERT_DATABASE_URL é usado internamente se DATABASE_URL não estiver setado)
      - DATABASE_URL=postgresql://${AUTH_DB_USER:-cspmexa_user}:${AUTH_DB_PASSWORD:-changeme}@postgres_auth_db:5432/${AUTH_DB_NAME:-cspmexa_db}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      # URL para o notification_service, usado pelo policy_engine para enviar notificações
      - NOTIFICATION_SERVICE_URL=http://notification_service:${NOTIFICATION_SERVICE_PORT:-8003}/api/v1
    volumes:
      - ./backend/policy_engine_service:/app
    ports:
      - "${POLICY_ENGINE_SERVICE_PORT:-8002}:8002"
    networks:
      - cspmexa_net
    depends_on:
      postgres_auth_db:
        condition: service_healthy
      # Adicionada dependência para garantir que notification_service esteja disponível, se necessário na inicialização.
      # Se a chamada for totalmente desacoplada (ex: via message queue no futuro), isso pode não ser estritamente necessário.
      # notification_service:
      #   condition: service_started # Ou service_healthy se tiver healthcheck

  notification_service:
    build:
      context: ./backend/notification_service
      dockerfile: Dockerfile
    container_name: cspmexa-notification-service
    restart: unless-stopped
    command: python /app/app/main.py # main.py lida com reload via DEBUG_MODE ou RELOAD_UVICORN
    environment:
      - PROJECT_NAME=NotificationService
      - API_V1_STR=/api/v1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RELOAD_UVICORN=${DEBUG_MODE:-false} # Usar DEBUG_MODE para consistência com outros serviços
      - PORT=${NOTIFICATION_SERVICE_PORT:-8003} # O Dockerfile usa PORT
      # SMTP settings from root .env file
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TLS=${SMTP_TLS:-true}
      - SMTP_SSL=${SMTP_SSL:-false}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - EMAILS_FROM_NAME=${EMAILS_FROM_NAME:-CSPMEXA Notification}
      - DEFAULT_CRITICAL_ALERT_RECIPIENT_EMAIL=${DEFAULT_CRITICAL_ALERT_RECIPIENT_EMAIL}
    volumes:
      - ./backend/notification_service/app:/app/app # Montar código para dev com reload
    ports:
      - "${NOTIFICATION_SERVICE_PORT:-8003}:8003" # Expor a porta
    networks:
      - cspmexa_net
    # depends_on: # Sem dependências de banco de dados para iniciar

  api_gateway_service:
    build:
      context: ./backend/api_gateway_service
      dockerfile: Dockerfile
    container_name: cspmexa-api-gateway-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000/api/v1
      - COLLECTOR_SERVICE_URL=http://collector_service:8001/api/v1
      - POLICY_ENGINE_SERVICE_URL=http://policy_engine_service:8002/api/v1
      - NOTIFICATION_SERVICE_URL=http://notification_service:${NOTIFICATION_SERVICE_PORT:-8003}/api/v1 # Adicionado
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?err_jwt_secret_missing_for_gateway}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - HTTP_CLIENT_TIMEOUT=${HTTP_CLIENT_TIMEOUT:-60}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    volumes:
      - ./backend/api_gateway_service:/app
    ports:
      - "${API_GATEWAY_PORT:-8050}:8050"
    networks:
      - cspmexa_net
    depends_on:
      - auth_service
      - collector_service
      - policy_engine_service
      - notification_service # Adicionado

  # --- Frontend WebApp ---
  frontend_webapp:
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile # Usa o Nginx do Dockerfile para servir o build de produção
      args: # Argumentos de build para passar a URL da API para o build do Vite
        VITE_API_BASE_URL: http://localhost:${API_GATEWAY_PORT:-8050}/api/v1
        # Ou, se o Nginx for fazer proxy, VITE_API_BASE_URL pode ser relativo: /api/v1
        # VITE_API_BASE_URL: /api/v1 # Se Nginx for configurado para proxy /api
    container_name: cspmexa-frontend-webapp
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:80" # Nginx no Dockerfile do frontend escuta na porta 80
    networks:
      - cspmexa_net
    depends_on:
      - api_gateway_service # Informativo, pois a conexão é do browser do usuário
    # Para desenvolvimento com hot-reload do Vite (requer modificação do Dockerfile do frontend para usar `npm run dev`):
    # command: npm run dev -- --host 0.0.0.0 # Para expor o Vite dev server
    # volumes:
    #   - ./frontend/webapp:/app # Monta todo o código
    #   - /app/node_modules # Volume anônimo para não sobrescrever node_modules do host
    # environment:
    #   - NODE_ENV=development
    #   - VITE_API_BASE_URL=http://localhost:${API_GATEWAY_PORT:-8050}/api/v1 # Para o Vite dev server
    # ports:
    #   - "${FRONTEND_PORT:-3000}:3000" # Porta do Vite dev server

# Definir o arquivo .env padrão que o Docker Compose vai procurar
# env_file: .env # Comentado pois docker-compose lê .env por padrão na mesma pasta
# Se quiser usar um nome diferente:
# env_file:
#   - ./.env.compose
# Mas o padrão é .env
# As variáveis nos services acima usam a sintaxe ${VAR:-default} para defaults
# ou ${VAR:?error_msg} para variáveis obrigatórias.
# Os usuários precisarão criar um arquivo .env na raiz do projeto.
# Um .env.example raiz será fornecido.
