version: '3.8'

networks:
  cspmexa_net:
    driver: bridge

volumes:
  postgres_auth_data:
  # Para desenvolvimento, podemos persistir node_modules do frontend se não quisermos reconstruir
  # frontend_node_modules:

services:
  # --- Banco de Dados ---
  postgres_auth_db:
    profiles: ["app"]
    image: postgres:13-alpine
    container_name: cspmexa-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${AUTH_DB_USER:-cspmexa_user}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD:-changeme}
      POSTGRES_DB: ${AUTH_DB_NAME:-cspmexa_db}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports: []
    networks:
      - cspmexa_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-cspmexa_user} -d $${POSTGRES_DB:-cspmexa_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- Serviços de Backend ---
  auth_service:
    profiles: ["app"]
    build:
      context: ./backend/auth_service
      dockerfile: Dockerfile
    container_name: cspmexa-auth-service
    restart: unless-stopped
    command: python /app/app/main.py # main.py lida com reload via DEBUG_MODE
    environment:
      - DATABASE_URL=postgresql://${AUTH_DB_USER:-cspmexa_user}:${AUTH_DB_PASSWORD:-changeme}@postgres_auth_db:5432/${AUTH_DB_NAME:-cspmexa_db}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:?err_jwt_secret_missing}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:${API_GATEWAY_PORT:-8050}/api/v1/auth/google/callback
      - FRONTEND_URL_AUTH_CALLBACK=http://localhost:${FRONTEND_PORT:-3000}/auth/callback
      - TOTP_ISSUER_NAME=${TOTP_ISSUER_NAME:-CSPMEXA}
      - DEBUG_MODE=${DEBUG_MODE:-false} # Para hot-reloading
    volumes:
      - ./backend/auth_service:/app # Monta o código para hot-reloading
    environment:
      # As configurações não-secretas ainda podem ser passadas por aqui
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-1440}
      - TOTP_ISSUER_NAME=${TOTP_ISSUER_NAME:-CSPMEXA}
      # Endereço do Vault para o cliente hvac
      - VAULT_ADDR=http://vault:8200
      # Token para autenticar no Vault (usando o token raiz de dev)
      - VAULT_TOKEN=root
    networks:
      - cspmexa_net
    depends_on:
      postgres_auth_db:
        condition: service_healthy
      vault-setup:
        condition: service_completed_successfully

  collector_service:
    profiles: ["app"]
    build:
      context: ./backend/collector_service
      dockerfile: Dockerfile
    container_name: cspmexa-collector-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      - AWS_REGION_NAME=${AWS_REGION_NAME:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/gcp-credentials.json
      - GOOGLE_SERVICE_ACCOUNT_KEY_PATH=/app/secrets/gws-sa-key.json
      - GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL=${GOOGLE_WORKSPACE_DELEGATED_ADMIN_EMAIL}
      - GOOGLE_WORKSPACE_CUSTOMER_ID=${GOOGLE_WORKSPACE_CUSTOMER_ID:-my_customer}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - HUAWEICLOUD_SDK_AK=${HUAWEICLOUD_SDK_AK}
      - HUAWEICLOUD_SDK_SK=${HUAWEICLOUD_SDK_SK}
      - HUAWEICLOUD_SDK_PROJECT_ID=${HUAWEICLOUD_SDK_PROJECT_ID}
      - HUAWEICLOUD_SDK_DOMAIN_ID=${HUAWEICLOUD_SDK_DOMAIN_ID}
      # Microsoft 365
      - M365_CLIENT_ID=${M365_CLIENT_ID}
      - M365_CLIENT_SECRET=${M365_CLIENT_SECRET}
      - M365_TENANT_ID=${M365_TENANT_ID}
      - M365_HTTP_CLIENT_TIMEOUT=${M365_HTTP_CLIENT_TIMEOUT:-30}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      # Conexão com o Vault
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./backend/collector_service:/app
      # Montar arquivos de credenciais JSON ainda pode ser necessário se não forem gerenciados pelo Vault
      - ${GCP_CREDENTIALS_PATH_HOST:-./secrets/gcp-credentials.json}:/app/secrets/gcp-credentials.json:ro
      - ${GWS_SA_KEY_PATH_HOST:-./secrets/gws-sa-key.json}:/app/secrets/gws-sa-key.json:ro
    networks:
      - cspmexa_net
    depends_on:
      - vault-setup

  policy_engine_service:
    profiles: ["app"]
    build:
      context: ./backend/policy_engine_service
      dockerfile: Dockerfile
    container_name: cspmexa-policy-engine-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - NOTIFICATION_SERVICE_URL=http://notification_service:8003/api/v1
      # Conexão com o Vault
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./backend/policy_engine_service:/app
    networks:
      - cspmexa_net
    depends_on:
      postgres_auth_db:
        condition: service_healthy
      vault-setup:
        condition: service_completed_successfully

  notification_service:
    profiles: ["app"]
    build:
      context: ./backend/notification_service
      dockerfile: Dockerfile
    container_name: cspmexa-notification-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      # Configs não-secretas
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - RELOAD_UVICORN=${DEBUG_MODE:-false}
      - EMAILS_FROM_EMAIL=${EMAILS_FROM_EMAIL}
      - EMAILS_FROM_NAME=${EMAILS_FROM_NAME:-CSPMEXA Notification}
      - DEFAULT_CRITICAL_ALERT_RECIPIENT_EMAIL=${DEFAULT_CRITICAL_ALERT_RECIPIENT_EMAIL}
      # Conexão com o Vault
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./backend/notification_service/app:/app/app
    networks:
      - cspmexa_net
    depends_on:
      vault-setup:
        condition: service_completed_successfully

  api_gateway_service:
    profiles: ["app"]
    build:
      context: ./backend/api_gateway_service
      dockerfile: Dockerfile
    container_name: cspmexa-api-gateway-service
    restart: unless-stopped
    command: python /app/app/main.py
    environment:
      # URLs dos serviços downstream são agora definidas no config.py, mas podem ser sobrescritas aqui se necessário.
      - HTTP_CLIENT_TIMEOUT=${HTTP_CLIENT_TIMEOUT:-60}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      # Conexão com o Vault
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./backend/api_gateway_service:/app
    networks:
      - cspmexa_net
    depends_on:
      - auth_service
      - collector_service
      - policy_engine_service
      - notification_service
      - vault-setup

  # --- Frontend Build ---
  frontend_build:
    profiles: ["app"]
    build:
      context: ./frontend/webapp
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api/v1
    volumes:
      - ./frontend/webapp/dist:/app/dist

  # --- Nginx Reverse Proxy ---
  nginx:
    profiles: ["app"]
    image: nginx:latest
    container_name: cspmexa-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./frontend/webapp/dist:/usr/share/nginx/html:ro
    networks:
      - cspmexa_net
    depends_on:
      - api_gateway_service
      - frontend_build

  # --- Serviço de Instalação (Wizard) ---
  # Este serviço não tem perfil, então ele roda por padrão com 'docker compose up'
  installer:
    build:
      context: ./installer
      dockerfile: Dockerfile
    container_name: cspmexa-installer
    ports:
      - "8080:8080" # Porta para o assistente de instalação web
    volumes:
      - .:/app/config # Monta a raiz do projeto para que o instalador possa criar o .env
      # Montar o socket do Docker para permitir que o instalador execute comandos docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cspmexa_net

  # --- Vault para Gestão de Segredos ---
  vault:
    image: hashicorp/vault:1.15
    container_name: cspmexa-vault
    ports:
      - "8200:8200"
    environment:
      # Roda o Vault em modo de desenvolvimento.
      # IMPORTANTE: NÃO USE EM PRODUÇÃO. O token raiz é 'root' e os dados são em memória.
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK # Evita que a memória do Vault seja trocada para o disco
    networks:
      - cspmexa_net

  # --- Serviço para configurar o Vault na primeira inicialização ---
  vault-setup:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: cspmexa-vault-setup
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root # Token raiz de desenvolvimento
    depends_on:
      vault:
        condition: service_started # Espera o serviço do vault iniciar
    networks:
      - cspmexa_net
    # Este serviço só precisa rodar uma vez. Em um ambiente real,
    # isso seria parte de um pipeline de CI/CD ou um processo de provisionamento.
    # Para o compose, podemos deixá-lo rodar e sair.
    # Se o script de setup for idempotente, não há problema em rodá-lo novamente.
