"""Add asset inventory tables

Revision ID: d003
Revises: d002
Create Date: 2025-07-17 04:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd003'
down_revision = 'd002' # Assumindo que a última migração foi a d002
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('provider', sa.Enum('AWS', 'GCP', 'AZURE', 'HUAWEI', 'GOOGLE_WORKSPACE', 'MICROSOFT_365', name='cloudproviderenum'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_assets_account_id'), 'cloud_assets', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_assets_asset_id'), 'cloud_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_cloud_assets_asset_type'), 'cloud_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_cloud_assets_id'), 'cloud_assets', ['id'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('target_asset_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['cloud_assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['cloud_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_relationships_id'), 'asset_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_relationships_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_cloud_assets_id'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_asset_type'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_asset_id'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_account_id'), table_name='cloud_assets')
    op.drop_table('cloud_assets')
    # ### end Alembic commands ###
