"""Add attack_paths table

Revision ID: d004
Revises: d003
Create Date: 2025-07-17 04:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd004'
down_revision = 'd003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', name='attackpathseverityenum'), nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id')
    )
    op.create_index(op.f('ix_attack_paths_id'), 'attack_paths', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_paths_id'), table_name='attack_paths')
    op.drop_table('attack_paths')
    # ### end Alembic commands ###
