"""Add linked_accounts table

Revision ID: d002
Revises: d001_update_user_role_to_enum
Create Date: 2025-07-17 03:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd002'
down_revision = 'd001_update_user_role_to_enum'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'GCP', 'AZURE', 'HUAWEI', 'GOOGLE_WORKSPACE', 'MICROSOFT_365', name='cloudproviderenum'), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_index(op.f('ix_linked_accounts_id'), 'linked_accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linked_accounts_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    # ### end Alembic commands ###
