"""create_users_table

Revision ID: placeholder_0001
Revises:
Create Date: 2024-03-10 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'placeholder_0001'
down_revision: Union[str, None] = None # Primeira migração
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False), # Default True
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.false(), nullable=False), # Default False
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('is_mfa_enabled', sa.Boolean(), server_default=sa.false(), nullable=False), # Default False
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), # Default now()
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, onupdate=sa.func.now()), # onupdate
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
