name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install backend dependencies
      run: |
        pip install -r backend/api_gateway_service/requirements.txt
        pip install -r backend/auth_service/requirements.txt
        pip install -r backend/collector_service/requirements.txt
        pip install -r backend/notification_service/requirements.txt
        pip install -r backend/policy_engine_service/requirements.txt
        pip install pytest pytest-asyncio httpx pytest-mock

    - name: Run backend tests
      run: |
        pytest backend/api_gateway_service/tests
        pytest backend/auth_service/tests
        pytest backend/collector_service/tests
        pytest backend/notification_service/tests
        pytest backend/policy_engine_service/tests

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      run: |
        cd frontend/webapp
        npm install

    - name: Run frontend tests
      run: |
        cd frontend/webapp
        npm test
